# Generated by Django 6.0.5 on 2026-05-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='running', max_length=16)),
                ('processed_categories', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запуск синхронизации',
                'verbose_name_plural': 'Запуски синхронизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_leaf', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('part', models.CharField(blank=True, max_length=128)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('barcodes', models.TextField(blank=True)),
                ('has_image', models.BooleanField(default=False)),
                ('multiplicity', models.PositiveIntegerField(default=0)),
                ('volume', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('warranty', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщика',
                'ordering': ['name', 'supplier_sku'],
            },
        ),
    ]
