# Generated by Django 6.0.5 on 2026-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='active_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='cost_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='nearest_logistic_center_qty',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='qty',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
