# Generated by Django 6.0.5 on 2026-05-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproduct_active_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Склад поставщика',
                'verbose_name_plural': 'Склады поставщика',
                'ordering': ['supplier_id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.PositiveIntegerField(unique=True)),
                ('address', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Адрес поставщика',
                'verbose_name_plural': 'Адреса поставщика',
                'ordering': ['supplier_id'],
            },
        ),
        migrations.CreateModel(
            name='AdultProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.PositiveIntegerField(unique=True)),
                ('characteristics', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adult_characteristics', to='catalog.supplierproduct')),
            ],
            options={
                'verbose_name': 'Характеристики товара 18+',
                'verbose_name_plural': 'Характеристики товаров 18+',
                'ordering': ['supplier_sku'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_image_id', models.PositiveIntegerField(unique=True)),
                ('supplier_sku', models.PositiveIntegerField(db_index=True)),
                ('url', models.CharField(max_length=1024)),
                ('deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.supplierproduct')),
            ],
            options={
                'verbose_name': 'Изображение товара поставщика',
                'verbose_name_plural': 'Изображения товаров поставщика',
                'ordering': ['supplier_sku', '-priority', 'supplier_image_id'],
            },
        ),
    ]
